## Arewa Data Science Academy
### Deep Learning Cohort1.0

#### Name: Temitope Bamidele
#### Email: bamideletemitope42@gmail.com
#### Title: Week 1 Solution

#####
2. create a random tensor with shape (7, 7)

In [1]:
import torch

In [2]:
# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.7806, 0.2250, 0.4477, 0.6612, 0.8114, 0.4882, 0.5636],
        [0.5558, 0.1170, 0.5133, 0.8325, 0.5072, 0.2592, 0.4066],
        [0.6882, 0.0928, 0.2978, 0.1493, 0.2858, 0.1300, 0.5400],
        [0.3433, 0.4052, 0.9103, 0.1833, 0.0037, 0.1587, 0.9017],
        [0.4070, 0.0453, 0.6057, 0.8006, 0.2805, 0.1670, 0.0927],
        [0.5690, 0.1335, 0.7782, 0.5772, 0.7171, 0.3413, 0.9752],
        [0.9930, 0.5644, 0.4058, 0.1333, 0.6048, 0.8472, 0.5907]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [3]:
random_tensor_2 = torch.rand(1, 7)
# Transposing the second random tensor
random_tensor_2 = random_tensor_2.T

In [4]:
# Matrix multiplication
torch.matmul(random_tensor, random_tensor_2)

tensor([[2.2732],
        [1.9242],
        [1.0031],
        [1.3744],
        [1.5832],
        [2.1036],
        [2.2496]])

4. Set the random seed to 0 and do 2 & 3 over again.

In [5]:
torch.random.manual_seed(seed=0)

random_tensor = torch.rand(7, 7)
random_tensor

random_tensor_2 = torch.rand(1, 7)
# Transposing the second random tensor
random_tensor_2 = random_tensor_2.T

# Matrix multiplication
torch.matmul(random_tensor, random_tensor_2)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?

In [6]:
torch.cuda.is_available()

False

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like

In [10]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

In [16]:
# setting random seed
torch.random.manual_seed(seed=1234)

# creating random tensors
rand1 = torch.rand(2, 3)
rand2 = torch.rand(2, 3)

# Moving tensors to GPU if available
tensor_on_gpu_1 = rand1.to(device)
tensor_on_gpu_2 = rand2.to(device)

print(tensor_on_gpu_1)
print(tensor_on_gpu_2)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


7. Perform a matrix multiplication on the tensors you created in 6

In [17]:
# Transposed one of the tensors  to match the inner dimension of the other
tensor_multiply = torch.matmul(rand1, rand2.T)
tensor_multiply

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

8. Find the maximum and minimum values of the output of 7

In [21]:
print(f"maximum value: {tensor_multiply.max()}")
print(f"minimum value: {tensor_multiply.min()}")

maximum value: 0.5617256760597229
minimum value: 0.3647301495075226


#### 9. Find the maximum and minimum index values of the output of 7

In [22]:
print(f"maximum value index: {tensor_multiply.argmax()}")
print(f"minimum value index: {tensor_multiply.argmin()}")

maximum value index: 3
minimum value index: 0


### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [28]:
# setting random seed
torch.random.manual_seed(seed=7)
rand_tensor_3 = torch.rand(1, 1, 1, 10)
torch.reshape(rand_tensor_3, (1,10))

tensor([[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]])

tensor([[0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757, 0.7842, 0.1525, 0.6662,
         0.3343]])